### ISSUE TITLE
Error in logs on startup

### ISSUE THREAD

**Issue by dmrickey** [theripper93/Splatter#32]
I'm getting this in my console log when my world starts up.

splatter v2.9.2
foundry v9 242
system pf1 0.80.7
```
foundry.js:316 TypeError: Cannot read properties of undefined (reading 'ColorSetting')
[Detected 1 package: splatter]
    at config.js:290:27
    at Function._call (foundry.js:294:14)
    at Function.callAll (foundry.js:253:12)
    at Game.setupGame (foundry.js:5547:11)
    at async Game._initializeGameView (foundry.js:6479:5)
    at async Game.initialize (foundry.js:5415:5)
```

**Comment by theripper93** [comment]
Do you have lib colorsettings enabled?

**Comment by dmrickey** [comment]
That appears to have been it. It must've been disabled during the v9 migration. I'm surprised Foundry doesn't have something built in to make sure that modules dependencies are also loaded on startup.
